name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Test Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Rust
        run: |
          rustup update
      
      - name: Test
        run: |
          cargo check
          cargo test --all

    